# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Bibata-Modern-Ice manual override (HYPR + X11)
exec-once = hyprctl setcursor Bibata-Modern-Ice 20

# Per-monitor wallpapers
exec-once = uwsm-app -- swaybg -o DP-1 -i $HOME/.local/share/omarchy/themes/nord/backgrounds/4-horizontal.jpg -m fill
exec-once = uwsm-app -- swaybg -o HDMI-A-1 -i $HOME/.local/share/omarchy/themes/nord/backgrounds/5-vertical.jpg -m fill
