# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Autostart processes from the default autostart
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = ! omarchy-toggle-enabled waybar-off && uwsm-app -- waybar
exec-once = uwsm-app -- swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = omarchy-powerprofiles-init
exec-once = uwsm-app -- omarchy-hyprland-monitor-watch

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all


# Per-monitor wallpapers utility
exec-once = uwsm-app -- xbg

# Hyprsunset to help with working late
exec-once = uwsm-app -- hyprsunset

# Bibata-Modern-Ice manual override (HYPR + X11)
exec-once = hyprctl setcursor Bibata-Modern-Ice 20

# Automatically closing Typora's license window
exec-once = ~/.config/hypr/scripts/close-typora-license.sh
