# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Hyprsunset to help with working late
exec-once = uwsm-app -- hyprsunset

# Bibata-Modern-Ice manual override (HYPR + X11)
exec-once = hyprctl setcursor Bibata-Modern-Ice 20

# Per-monitor wallpapers
exec-once = pkill -x swaybg
exec-once = uwsm-app -- swaybg -o DP-1 -i $HOME/dotfiles/stow/wallpapers/.config/omarchy/backgrounds/hinterlands/\$-horizontal-00.jpg -m fill
exec-once = uwsm-app -- swaybg -o HDMI-A-1 -i $HOME/dotfiles/stow/wallpapers/.config/omarchy/backgrounds/hinterlands/\#-vertical-11.jpeg -m fill

# Automatically closing Typora's license window
exec-once = ~/.config/hypr/scripts/close-typora-license.sh
