
# NVIDIA
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# 1080p SCALING
env = GDK_SCALE,1

# Bibata-Modern-Ice ENV VARS
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,20
env = XCURSOR_SIZE,20

# Path override for user applications
env = PATH,$HOME/.local/bin:$PATH
