# Change the default Omarchy look'n'feel

$activeBorderColor = rgb(cacaca)

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
    col.active_border = $activeBorderColor
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
    shadow {
        enabled = false
    }

    screen_shader = ~/.config/hypr/shaders/grayscale.glsl
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
