# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- keepassxc

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://mail.google.com/mail/u/0/#inbox"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, D, YouTube Music, exec, omarchy-launch-webapp "https://music.youtube.com/"
bindd = SUPER SHIFT, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Unbind the GTK Scaling bind
unbind = SUPER, Slash

# move to scratchpad rebind
unbind = SUPER ALT, S
bindd = SUPER SHIFT, S, Move window to scratchpad, movetoworkspacesilent, special:scratchpad

# Only display the OSD on the currently focused monitor
$osdclient = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"

unbind = SUPER, mouse_up
unbind = SUPER, mouse_down

# F21 - F23: Language Binds
bindd = CTRL ALT SHIFT, 1, English, exec, hyprctl switchxkblayout current 0 >/dev/null  # F21
bindd = CTRL ALT SHIFT, 2, Russian, exec, hyprctl switchxkblayout current 2 >/dev/null  # F23
bindd = CTRL ALT SHIFT, 3, Ukrainian, exec, hyprctl switchxkblayout current 1 >/dev/null  # F22

# Alt + scroll wheel to manage output volume (5% steps)
bindld = ALT, mouse_up, Volume up with scroll, exec, $osdclient --output-volume raise
bindld = ALT, mouse_down, Volume down with scroll, exec, $osdclient --output-volume lower

# Ctrl + scroll wheel to manage output volume (1% steps)
bindld = SUPER, mouse_up, Volume up precise, exec, $osdclient --output-volume +1 
bindld = SUPER, mouse_down, Volume down precise, exec, $osdclient --output-volume -1

# Unbinding the default screenshot utils
unbind = ALT SHIFT, S
unbind = , PRINT

# Alt + Shift + S & PrtSc bind to a custom util
bindd = ALT SHIFT, S, Screenshot, exec, $HOME/src/screenshot-to-obsidian/main.sh
bindd = , PRINT, Screenshot-PrtSc, exec, $HOME/src/screenshot-to-obsidian/main.sh

