# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# fallback
monitor=,preferred,auto,1

# 1920x1080@120, horizontal
monitor = desc:AOC 24G4 12VR1HA013617, 1920x1080@120, 0x0, 1, transform, 2

# 1080x1920@75 for 4070 & 1650, vertical
monitor = desc:LG Electronics LG FULL HD 0x01010101, 1920x1080@75, 1920x-840, 1, transform, 3

# odd workspaces - horizontal
workspace = 1, monitor:desc:AOC 24G4 12VR1HA013617, default:true
workspace = 3, monitor:desc:AOC 24G4 12VR1HA013617
workspace = 5, monitor:desc:AOC 24G4 12VR1HA013617
workspace = 7, monitor:desc:AOC 24G4 12VR1HA013617
workspace = 9, monitor:desc:AOC 24G4 12VR1HA013617

# even workspaces - vertical
workspace = 2, monitor:desc:LG Electronics LG FULL HD 0x01010101, default:true
workspace = 4, monitor:desc:LG Electronics LG FULL HD 0x01010101
workspace = 6, monitor:desc:LG Electronics LG FULL HD 0x01010101
workspace = 8, monitor:desc:LG Electronics LG FULL HD 0x01010101
workspace = 10, monitor:desc:LG Electronics LG FULL HD 0x01010101
